### ISSUE TITLE
Prerendered images never get updated

### ISSUE THREAD

**Issue by che-** [52North/timeseries-api#92]
I configured image prerendering by phenomenon, the images are rendered once the tomcat server starts but never get updated afterwards. The configured update interval of 5 Minutes is ignored:

	<bean id="preRenderingTask" class="org.n52.io.PreRenderingTask"
		destroy-method="shutdownTask" factory-method="createTask">
		<property name="timeseriesMetadataService" ref="timeseriesService" />
		<property name="timeseriesDataService" ref="timeseriesService" />
		<property name="outputPath" value="generated/prerendered" />
		<property name="width" value="800" />
		<property name="height" value="500" />
		<property name="language" value="de" />
		<property name="showGrid" value="true" />
		<property name="periodInMinutes" value="5" />
		<property name="enabled" value="true" />
	</bean>

**Comment by ridoo** [comment]
I checked and added a `setLastModified` when file gets updated (see 850be30fd6e74ab920822290f1a830df068bf9d5).

However, please double check during your retest if the image gets updated or not. Do not trust the Windows Explorer `Date` and open the file properties via context menu instead (or just use the `cmd` tool to find out). It appears that the `last modified` property will be updated but the `created` property won't.
