### ISSUE TITLE
Installation and use timeseries-api

### ISSUE THREAD

**Issue by lottaa** [52North/timeseries-api#97]
I checked out the latest timeseries-api. When I want to build the WAR file using the Termial (mvn clean install)... I get an error message.
Is there any description how to install and use the timeseries-api? I couldn´t find anything.

**Comment by ridoo** [comment]
@lottaa what kind of error message do you get?

**Comment by lottaa** [comment]
Here you are the error message. Don´t wonder I changed the pathname with xxx.

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Sensor Web Timeseries API
[INFO] Sensor Web Timeseries API - IO
[INFO] Sensor Web Timeseries API - SPI
[INFO] Sensor Web Timeseries API - REST Binding
[INFO] Sensor Web Timeseries API - SPI Implementations
[INFO] Sensor Web Timeseries API - SPI Impl DAO
[INFO] Sensor Web Timeseries API - Webapp
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Sensor Web Timeseries API 1.4.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ timeseries-api ---
[INFO] Deleting xxx\timeseries-api\target
[INFO]
[INFO] --- git-commit-id-plugin:2.1.10:revision (git-commit-id) @ timeseries-api---
[INFO]
[INFO] --- gmaven-plugin:1.0:execute (default) @ timeseries-api ---
[INFO]
[INFO] --- license-maven-plugin:2.2:check (check-license) @ timeseries-api ---
[INFO] Checking licenses...
[INFO]
[INFO] --- maven-notice-plugin:1.0.6:check (check-license) @ timeseries-api ---
[INFO] Loading license lookup mappings from 'http://52north.github.io/cdn/licenses/license-mappings.xml'
[INFO] Parsing Dependencies for: Sensor Web Timeseries API
[INFO] Parsing Dependencies for: Sensor Web Timeseries API - IO
[INFO] Parsing Dependencies for: Sensor Web Timeseries API - SPI
[INFO] Parsing Dependencies for: Sensor Web Timeseries API - REST Binding
[INFO] Parsing Dependencies for: Sensor Web Timeseries API - Webapp
[INFO] Parsing Dependencies for: Sensor Web Timeseries API - SPI Impl DAO
[INFO] Parsing Dependencies for: Sensor Web Timeseries API - SPI Implementations
[INFO] Parsing Dependencies for: Sensor Web Timeseries API - SPI Impl DAO
[ERROR] Existing NOTICE file 'xxx\timeseries-api\NOTICE' doesn't match expected NOTICE file: xxx\timeseries-api\target\NOTICE.expected 65a65 ---
>   JavaMelody - Core under LGPL 74a75 ---
>   JRobin under LGPL

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Sensor Web Timeseries API .......................... FAILURE [ 15.477 s]
[INFO] Sensor Web Timeseries API - IO ..................... SKIPPED
[INFO] Sensor Web Timeseries API - SPI .................... SKIPPED
[INFO] Sensor Web Timeseries API - REST Binding ........... SKIPPED
[INFO] Sensor Web Timeseries API - SPI Implementations .... SKIPPED
[INFO] Sensor Web Timeseries API - SPI Impl DAO ........... SKIPPED
[INFO] Sensor Web Timeseries API - Webapp ................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.526 s
[INFO] Finished at: 2015-04-14T17:05:07+02:00
[INFO] Final Memory: 22M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jasig.maven:maven-notice-plugin:1.0.6:check (
check-license) on project timeseries-api: Existing NOTICE file 'xxx\timeseries-api\NOTICE' doesn't match expected NOTICE file:
xxx\timeseries-api\target\NOTICE.expected -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by ridoo** [comment]
you can circumvent this issue by running `mvn clean notice:generate install`
